package net.luckystudio.cozyhome.client;

import net.minecraft.world.level.block.Blocks;

import net.luckystudio.cozyhome.block.ModBlocks;
import net.luckystudio.cozyhome.block.util.ModBlockUtilities;
import net.luckystudio.cozyhome.item.ModItems;
import net.luckystudio.cozyhome.util.ModColorHandler;
import net.minecraft.world.level.BlockAndTintGetter;
import net.minecraft.core.BlockPos;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.core.component.DataComponents;
import net.minecraft.world.item.component.DyedItemColor;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.block.Block;

public class ModRenderLayers {

    /** Tint for the blocks that can hold water or other liquids. */
    public static int containsColor(BlockState state, BlockAndTintGetter world, BlockPos pos, int tintIndex) {
        return ModBlockUtilities.getColorFromContainsState(state, world, pos);
    }

    /** Tint for the blocks that are dyed through their block entity. */
    public static int dyedBlockColor(BlockState state, BlockAndTintGetter world, BlockPos pos, int tintIndex) {
        if (world == null || pos == null) return -17170434;
        return ModColorHandler.getBlockColor(world.getBlockEntity(pos), -17170434);
    }

    /** Tint for the items that are dyed. */
    public static int dyedItemColor(ItemStack stack, int tintIndex) {
        return DyedItemColor.getOrDefault(stack, -17170434);
    }

    public static Block[] cutoutBlocks() {
        return new Block[]{
                ModBlocks.OAK_TOOL_RACK,
                ModBlocks.SPRUCE_TOOL_RACK,
                ModBlocks.BIRCH_TOOL_RACK,
                ModBlocks.JUNGLE_TOOL_RACK,
                ModBlocks.ACACIA_TOOL_RACK,
                ModBlocks.DARK_OAK_TOOL_RACK,
                ModBlocks.MANGROVE_TOOL_RACK,
                ModBlocks.CHERRY_TOOL_RACK,
                ModBlocks.BAMBOO_TOOL_RACK,
                ModBlocks.CRIMSON_TOOL_RACK,
                ModBlocks.WARPED_TOOL_RACK,
                ModBlocks.IRON_TOOL_RACK,
                ModBlocks.GLASS_TOOL_RACK,
                ModBlocks.UNDEAD_TOOL_RACK,
                ModBlocks.OMINOUS_TOOL_RACK,
                ModBlocks.TENT,
                ModBlocks.OAK_SINK_COUNTER,
                ModBlocks.SPRUCE_SINK_COUNTER,
                ModBlocks.BIRCH_SINK_COUNTER,
                ModBlocks.JUNGLE_SINK_COUNTER,
                ModBlocks.ACACIA_SINK_COUNTER,
                ModBlocks.DARK_OAK_SINK_COUNTER,
                ModBlocks.MANGROVE_SINK_COUNTER,
                ModBlocks.CHERRY_SINK_COUNTER,
                ModBlocks.BAMBOO_SINK_COUNTER,
                ModBlocks.CRIMSON_SINK_COUNTER,
                ModBlocks.WARPED_SINK_COUNTER,
                ModBlocks.OAK_TABLE,
                ModBlocks.SPRUCE_TABLE,
                ModBlocks.BIRCH_TABLE,
                ModBlocks.JUNGLE_TABLE,
                ModBlocks.ACACIA_TABLE,
                ModBlocks.DARK_OAK_TABLE,
                ModBlocks.MANGROVE_TABLE,
                ModBlocks.CHERRY_TABLE,
                ModBlocks.BAMBOO_TABLE,
                ModBlocks.CRIMSON_TABLE,
                ModBlocks.WARPED_TABLE,
                ModBlocks.IRON_TABLE,
                ModBlocks.GLASS_TABLE,
                ModBlocks.OMINOUS_TABLE,
                ModBlocks.UNDEAD_TABLE,
                ModBlocks.OAK_LAMP,
                ModBlocks.SPRUCE_LAMP,
                ModBlocks.BIRCH_LAMP,
                ModBlocks.JUNGLE_LAMP,
                ModBlocks.ACACIA_LAMP,
                ModBlocks.DARK_OAK_LAMP,
                ModBlocks.MANGROVE_LAMP,
                ModBlocks.CHERRY_LAMP,
                ModBlocks.BAMBOO_LAMP,
                ModBlocks.CRIMSON_LAMP,
                ModBlocks.WARPED_LAMP,
                ModBlocks.IRON_LAMP,
                ModBlocks.GLASS_LAMP,
                ModBlocks.UNDEAD_LAMP,
                ModBlocks.OMINOUS_LAMP,
                ModBlocks.OAK_WALL_MIRROR,
                ModBlocks.SPRUCE_WALL_MIRROR,
                ModBlocks.BIRCH_WALL_MIRROR,
                ModBlocks.JUNGLE_WALL_MIRROR,
                ModBlocks.ACACIA_WALL_MIRROR,
                ModBlocks.DARK_OAK_WALL_MIRROR,
                ModBlocks.MANGROVE_WALL_MIRROR,
                ModBlocks.CHERRY_WALL_MIRROR,
                ModBlocks.BAMBOO_WALL_MIRROR,
                ModBlocks.CRIMSON_WALL_MIRROR,
                ModBlocks.WARPED_WALL_MIRROR,
                ModBlocks.OAK_WALL_CLOCK,
                ModBlocks.SPRUCE_WALL_CLOCK,
                ModBlocks.BIRCH_WALL_CLOCK,
                ModBlocks.JUNGLE_WALL_CLOCK,
                ModBlocks.ACACIA_WALL_CLOCK,
                ModBlocks.DARK_OAK_WALL_CLOCK,
                ModBlocks.MANGROVE_WALL_CLOCK,
                ModBlocks.CHERRY_WALL_CLOCK,
                ModBlocks.BAMBOO_WALL_CLOCK,
                ModBlocks.CRIMSON_WALL_CLOCK,
                ModBlocks.WARPED_WALL_CLOCK,
                ModBlocks.TELESCOPE
        };
    }

    /** Fountains and spouts draw their water as part of the block, so they need the translucent layer to show it see-through (also with shaders). */
    public static Block[] translucentBlocks() {
        return new Block[]{
                ModBlocks.STONE_BRICK_FOUNTAIN,
                ModBlocks.STONE_BRICK_FOUNTAIN_SPOUT,
                ModBlocks.MOSSY_STONE_BRICK_FOUNTAIN,
                ModBlocks.MOSSY_STONE_BRICK_FOUNTAIN_SPOUT,
                ModBlocks.GRANITE_FOUNTAIN,
                ModBlocks.GRANITE_FOUNTAIN_SPOUT,
                ModBlocks.DIORITE_FOUNTAIN,
                ModBlocks.DIORITE_FOUNTAIN_SPOUT,
                ModBlocks.ANDESITE_FOUNTAIN,
                ModBlocks.ANDESITE_FOUNTAIN_SPOUT,
                ModBlocks.DEEPSLATE_FOUNTAIN,
                ModBlocks.DEEPSLATE_FOUNTAIN_SPOUT,
                ModBlocks.CALCITE_FOUNTAIN,
                ModBlocks.CALCITE_FOUNTAIN_SPOUT,
                ModBlocks.TUFF_FOUNTAIN,
                ModBlocks.TUFF_FOUNTAIN_SPOUT,
                ModBlocks.BRICK_FOUNTAIN,
                ModBlocks.BRICK_FOUNTAIN_SPOUT,
                ModBlocks.MUD_FOUNTAIN,
                ModBlocks.MUD_FOUNTAIN_SPOUT,
                ModBlocks.SANDSTONE_FOUNTAIN,
                ModBlocks.SANDSTONE_FOUNTAIN_SPOUT,
                ModBlocks.RED_SANDSTONE_FOUNTAIN,
                ModBlocks.RED_SANDSTONE_FOUNTAIN_SPOUT,
                ModBlocks.PRISMARINE_FOUNTAIN,
                ModBlocks.PRISMARINE_FOUNTAIN_SPOUT,
                ModBlocks.NETHER_BRICK_FOUNTAIN,
                ModBlocks.NETHER_BRICK_FOUNTAIN_SPOUT,
                ModBlocks.RED_NETHER_BRICK_FOUNTAIN,
                ModBlocks.RED_NETHER_BRICK_FOUNTAIN_SPOUT,
                ModBlocks.BLACKSTONE_FOUNTAIN,
                ModBlocks.BLACKSTONE_FOUNTAIN_SPOUT,
                ModBlocks.ENDSTONE_FOUNTAIN,
                ModBlocks.ENDSTONE_FOUNTAIN_SPOUT,
                ModBlocks.PURPUR_FOUNTAIN,
                ModBlocks.PURPUR_FOUNTAIN_SPOUT,
        };
    }

    public static Block[] containsBlocks() {
        return new Block[]{
                ModBlocks.OAK_SINK_COUNTER,
                ModBlocks.SPRUCE_SINK_COUNTER,
                ModBlocks.BIRCH_SINK_COUNTER,
                ModBlocks.JUNGLE_SINK_COUNTER,
                ModBlocks.ACACIA_SINK_COUNTER,
                ModBlocks.DARK_OAK_SINK_COUNTER,
                ModBlocks.MANGROVE_SINK_COUNTER,
                ModBlocks.CHERRY_SINK_COUNTER,
                ModBlocks.BAMBOO_SINK_COUNTER,
                ModBlocks.CRIMSON_SINK_COUNTER,
                ModBlocks.WARPED_SINK_COUNTER,
                ModBlocks.STONE_BRICK_SINK,
                ModBlocks.MOSSY_STONE_BRICK_SINK,
                ModBlocks.GRANITE_SINK,
                ModBlocks.DIORITE_SINK,
                ModBlocks.ANDESITE_SINK,
                ModBlocks.DEEPSLATE_SINK,
                ModBlocks.CALCITE_SINK,
                ModBlocks.TUFF_SINK,
                ModBlocks.BRICK_SINK,
                ModBlocks.MUD_SINK,
                ModBlocks.SANDSTONE_SINK,
                ModBlocks.RED_SANDSTONE_SINK,
                ModBlocks.PRISMARINE_SINK,
                ModBlocks.NETHER_BRICK_SINK,
                ModBlocks.RED_NETHER_BRICK_SINK,
                ModBlocks.BLACKSTONE_SINK,
                ModBlocks.ENDSTONE_SINK,
                ModBlocks.PURPUR_SINK,
                ModBlocks.IRON_SINK,
                ModBlocks.GOLD_SINK,
                ModBlocks.STONE_BRICK_BATHTUB,
                ModBlocks.MOSSY_STONE_BRICK_BATHTUB,
                ModBlocks.GRANITE_BATHTUB,
                ModBlocks.DIORITE_BATHTUB,
                ModBlocks.ANDESITE_BATHTUB,
                ModBlocks.DEEPSLATE_BATHTUB,
                ModBlocks.CALCITE_BATHTUB,
                ModBlocks.TUFF_BATHTUB,
                ModBlocks.BRICK_BATHTUB,
                ModBlocks.MUD_BATHTUB,
                ModBlocks.SANDSTONE_BATHTUB,
                ModBlocks.RED_SANDSTONE_BATHTUB,
                ModBlocks.PRISMARINE_BATHTUB,
                ModBlocks.NETHER_BRICK_BATHTUB,
                ModBlocks.RED_NETHER_BRICK_BATHTUB,
                ModBlocks.BLACKSTONE_BATHTUB,
                ModBlocks.ENDSTONE_BATHTUB,
                ModBlocks.PURPUR_BATHTUB,
                ModBlocks.IRON_BATHTUB,
                ModBlocks.GOLD_BATHTUB,
                ModBlocks.STONE_BRICK_FOUNTAIN,
                ModBlocks.STONE_BRICK_FOUNTAIN_SPOUT,
                ModBlocks.MOSSY_STONE_BRICK_FOUNTAIN,
                ModBlocks.MOSSY_STONE_BRICK_FOUNTAIN_SPOUT,
                ModBlocks.GRANITE_FOUNTAIN,
                ModBlocks.GRANITE_FOUNTAIN_SPOUT,
                ModBlocks.DIORITE_FOUNTAIN,
                ModBlocks.DIORITE_FOUNTAIN_SPOUT,
                ModBlocks.ANDESITE_FOUNTAIN,
                ModBlocks.ANDESITE_FOUNTAIN_SPOUT,
                ModBlocks.DEEPSLATE_FOUNTAIN,
                ModBlocks.DEEPSLATE_FOUNTAIN_SPOUT,
                ModBlocks.CALCITE_FOUNTAIN,
                ModBlocks.CALCITE_FOUNTAIN_SPOUT,
                ModBlocks.TUFF_FOUNTAIN,
                ModBlocks.TUFF_FOUNTAIN_SPOUT,
                ModBlocks.BRICK_FOUNTAIN,
                ModBlocks.BRICK_FOUNTAIN_SPOUT,
                ModBlocks.MUD_FOUNTAIN,
                ModBlocks.MUD_FOUNTAIN_SPOUT,
                ModBlocks.SANDSTONE_FOUNTAIN,
                ModBlocks.SANDSTONE_FOUNTAIN_SPOUT,
                ModBlocks.RED_SANDSTONE_FOUNTAIN,
                ModBlocks.RED_SANDSTONE_FOUNTAIN_SPOUT,
                ModBlocks.PRISMARINE_FOUNTAIN,
                ModBlocks.PRISMARINE_FOUNTAIN_SPOUT,
                ModBlocks.NETHER_BRICK_FOUNTAIN,
                ModBlocks.NETHER_BRICK_FOUNTAIN_SPOUT,
                ModBlocks.RED_NETHER_BRICK_FOUNTAIN,
                ModBlocks.RED_NETHER_BRICK_FOUNTAIN_SPOUT,
                ModBlocks.BLACKSTONE_FOUNTAIN,
                ModBlocks.BLACKSTONE_FOUNTAIN_SPOUT,
                ModBlocks.ENDSTONE_FOUNTAIN,
                ModBlocks.ENDSTONE_FOUNTAIN_SPOUT,
                ModBlocks.PURPUR_FOUNTAIN,
                ModBlocks.PURPUR_FOUNTAIN_SPOUT,
                ModBlocks.FALLING_LIQUID
        };
    }

    public static Block[] dyedBlocks() {
        return new Block[]{
                ModBlocks.TENT,
                ModBlocks.OAK_MIRROR_STAND,
                ModBlocks.SPRUCE_MIRROR_STAND,
                ModBlocks.BIRCH_MIRROR_STAND,
                ModBlocks.JUNGLE_MIRROR_STAND,
                ModBlocks.ACACIA_MIRROR_STAND,
                ModBlocks.DARK_OAK_MIRROR_STAND,
                ModBlocks.MANGROVE_MIRROR_STAND,
                ModBlocks.CHERRY_MIRROR_STAND,
                ModBlocks.BAMBOO_MIRROR_STAND,
                ModBlocks.CRIMSON_MIRROR_STAND,
                ModBlocks.WARPED_MIRROR_STAND,
                ModBlocks.STUMP_CHAIR,
                ModBlocks.OAK_BENCH,
                ModBlocks.SPRUCE_BENCH,
                ModBlocks.BIRCH_BENCH,
                ModBlocks.JUNGLE_BENCH,
                ModBlocks.ACACIA_BENCH,
                ModBlocks.DARK_OAK_BENCH,
                ModBlocks.MANGROVE_BENCH,
                ModBlocks.CHERRY_BENCH,
                ModBlocks.BAMBOO_BENCH,
                ModBlocks.CRIMSON_BENCH,
                ModBlocks.WARPED_BENCH,
                ModBlocks.OAK_COUCH,
                ModBlocks.SPRUCE_COUCH,
                ModBlocks.BIRCH_COUCH,
                ModBlocks.JUNGLE_COUCH,
                ModBlocks.ACACIA_COUCH,
                ModBlocks.DARK_OAK_COUCH,
                ModBlocks.MANGROVE_COUCH,
                ModBlocks.CHERRY_COUCH,
                ModBlocks.BAMBOO_COUCH,
                ModBlocks.CRIMSON_COUCH,
                ModBlocks.WARPED_COUCH,
                ModBlocks.OAK_LAMP,
                ModBlocks.SPRUCE_LAMP,
                ModBlocks.BIRCH_LAMP,
                ModBlocks.JUNGLE_LAMP,
                ModBlocks.ACACIA_LAMP,
                ModBlocks.DARK_OAK_LAMP,
                ModBlocks.MANGROVE_LAMP,
                ModBlocks.CHERRY_LAMP,
                ModBlocks.BAMBOO_LAMP,
                ModBlocks.CRIMSON_LAMP,
                ModBlocks.WARPED_LAMP,
                ModBlocks.IRON_LAMP,
                ModBlocks.GLASS_LAMP,
                ModBlocks.UNDEAD_LAMP,
                ModBlocks.OMINOUS_LAMP
        };
    }

    public static Item[] dyedItems() {
        return new Item[]{
                ModItems.CUSHION,
                ModBlocks.TENT.asItem(),
                ModBlocks.OAK_COUCH.asItem(),
                ModBlocks.SPRUCE_COUCH.asItem(),
                ModBlocks.BIRCH_COUCH.asItem(),
                ModBlocks.JUNGLE_COUCH.asItem(),
                ModBlocks.ACACIA_COUCH.asItem(),
                ModBlocks.DARK_OAK_COUCH.asItem(),
                ModBlocks.MANGROVE_COUCH.asItem(),
                ModBlocks.CHERRY_COUCH.asItem(),
                ModBlocks.BAMBOO_COUCH.asItem(),
                ModBlocks.CRIMSON_COUCH.asItem(),
                ModBlocks.WARPED_COUCH.asItem(),
                ModBlocks.OAK_LAMP.asItem(),
                ModBlocks.SPRUCE_LAMP.asItem(),
                ModBlocks.BIRCH_LAMP.asItem(),
                ModBlocks.JUNGLE_LAMP.asItem(),
                ModBlocks.ACACIA_LAMP.asItem(),
                ModBlocks.DARK_OAK_LAMP.asItem(),
                ModBlocks.MANGROVE_LAMP.asItem(),
                ModBlocks.CHERRY_LAMP.asItem(),
                ModBlocks.BAMBOO_LAMP.asItem(),
                ModBlocks.CRIMSON_LAMP.asItem(),
                ModBlocks.WARPED_LAMP.asItem(),
                ModBlocks.IRON_LAMP.asItem(),
                ModBlocks.GLASS_LAMP.asItem(),
                ModBlocks.UNDEAD_LAMP.asItem(),
                ModBlocks.OMINOUS_LAMP.asItem()
        };
    }
}
